[build-system]
requires = ["setuptools>=45<60", "setuptools_scm[toml]>=6.4"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "kasushi/_version.py"
local_scheme = "no-local-version"

[tool.pytest.ini_options]
minversion = "6.0"
log_cli = "True"
